#!/usr/bin/env python3
"""
Hourly Summarization Script — TSAR Monitoring Data
====================================================
Materializes the v_tsar_hourly view into the tsar_hourly table and exports
the result to CSV for external analysis.

Usage:
    python hourly_summary.py

Requires:
    tsar_monitor.db (generated by etl_import.py first)

Output:
    - Populates tsar_hourly table with aggregated hourly data
    - Exports tsar_hourly.csv
    - Prints summary statistics
"""

import csv
import sqlite3
import os
import time

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
DB_PATH  = os.path.join(BASE_DIR, "tsar_monitor.db")
CSV_PATH = os.path.join(BASE_DIR, "tsar_hourly.csv")


# ---------------------------------------------------------------------------
# Materialize hourly summary
# ---------------------------------------------------------------------------

def materialize_hourly(conn: sqlite3.Connection) -> int:
    """
    Populate tsar_hourly table from v_tsar_hourly view.
    Uses INSERT OR REPLACE for idempotent re-runs.

    Returns:
        Number of rows inserted.
    """
    print("[HOURLY] Materializing tsar_hourly from v_tsar_hourly ...")
    conn.execute("DELETE FROM tsar_hourly")  # clear stale data
    conn.execute(
        "INSERT INTO tsar_hourly (hour_bucket, hostid, type, mod, tag, "
        "avg_value, max_value, min_value, sample_count) "
        "SELECT hour_bucket, hostid, type, mod, tag, "
        "avg_value, max_value, min_value, sample_count "
        "FROM v_tsar_hourly"
    )
    conn.commit()
    count = conn.execute("SELECT COUNT(*) FROM tsar_hourly").fetchone()[0]
    print(f"[HOURLY] {count:,} rows materialized into tsar_hourly.")
    return count


# ---------------------------------------------------------------------------
# Export to CSV
# ---------------------------------------------------------------------------

def export_csv(conn: sqlite3.Connection) -> None:
    """
    Export tsar_hourly table to CSV with header.

    By default exports all rows. The query can be filtered to export
    only performance or only disk data.
    """
    print(f"[EXPORT] Writing {CSV_PATH} ...")

    cursor = conn.execute(
        "SELECT hour_bucket, hostid, type, mod, tag, "
        "avg_value, max_value, min_value, sample_count "
        "FROM tsar_hourly "
        "ORDER BY hour_bucket, hostid, type, mod"
    )

    with open(CSV_PATH, "w", encoding="utf-8-sig", newline="") as f:
        writer = csv.writer(f)
        writer.writerow([
            "hour_bucket", "hostid", "type", "mod", "tag",
            "avg_value", "max_value", "min_value", "sample_count",
        ])
        writer.writerows(cursor)

    size_kb = os.path.getsize(CSV_PATH) / 1024
    print(f"[EXPORT] Done — {size_kb:.0f} KB written.")


# ---------------------------------------------------------------------------
# Summary statistics
# ---------------------------------------------------------------------------

def print_stats(conn: sqlite3.Connection) -> None:
    """Print a few useful statistics from the hourly summary."""

    queries = {
        "Total hourly buckets": "SELECT COUNT(DISTINCT hour_bucket) FROM tsar_hourly",
        "Hosts covered": "SELECT COUNT(DISTINCT hostid) FROM tsar_hourly",
        "Metrics covered": "SELECT COUNT(DISTINCT mod) FROM tsar_hourly",
        "Total rows": "SELECT COUNT(*) FROM tsar_hourly",
    }

    print()
    print("=" * 50)
    print("  HOURLY SUMMARY STATISTICS")
    print("=" * 50)
    for label, sql in queries.items():
        val = conn.execute(sql).fetchone()[0]
        print(f"  {label:.<30s} {val:>8,}")

    # Time range
    t_min, t_max = conn.execute(
        "SELECT MIN(hour_bucket), MAX(hour_bucket) FROM tsar_hourly"
    ).fetchone()
    print(f"  {'Time range':.<30s} {t_min} → {t_max}")

    # Sample: top 5 disk util hosts by peak
    print()
    print("  Top 5 hosts by peak sda_util (%):")
    for row in conn.execute(
        "SELECT hostid, MAX(max_value) AS peak_util "
        "FROM tsar_hourly WHERE mod='sda_util' "
        "GROUP BY hostid ORDER BY peak_util DESC LIMIT 5"
    ):
        print(f"    {row[0]}  peak={row[1]:.1f}%")

    # Sample: avg CPU usage across all hosts
    avg_cpu = conn.execute(
        "SELECT ROUND(AVG(avg_value), 2) FROM tsar_hourly WHERE mod='cpu_usage'"
    ).fetchone()[0]
    print(f"\n  Overall avg CPU usage: {avg_cpu}%")
    print("=" * 50)


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    if not os.path.exists(DB_PATH):
        print(f"[ERROR] Database not found: {DB_PATH}")
        print("Run 'python etl_import.py' first to create the database.")
        return

    start_time = time.time()
    conn = sqlite3.connect(DB_PATH)

    try:
        n_rows = materialize_hourly(conn)
        export_csv(conn)
        print_stats(conn)
        elapsed = time.time() - start_time
        print(f"\nDone in {elapsed:.1f}s")
    finally:
        conn.close()


if __name__ == "__main__":
    main()
